version: '3.5'
services:
  php:
    env_file: .env
    build:
      context: docker/images/php-fpm7.4
      args:
        UID: ${HOST_UID}
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ${RELATIVE_APP_PATH}:/var/www/html